name: znajdz_przepis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  flutter_bloc: ^9.0.0
  provider: ^6.0.0

  # Backend & API
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

  # Data Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Utilities
  equatable: ^2.0.7
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
