// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPl2cZt27ZqjE3uIj9C-Er6mPLInFkijE',
    appId: '1:196295581571:web:084cc2707e686e55fd60b6',
    messagingSenderId: '196295581571',
    projectId: 'project-wcag',
    authDomain: 'project-wcag.firebaseapp.com',
    storageBucket: 'project-wcag.firebasestorage.app',
    measurementId: 'G-M0G0MW6JCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6GMq9ENuZdYyRVPCdtwFsI3A0TFTVQw',
    appId: '1:196295581571:android:278c2db91261301cfd60b6',
    messagingSenderId: '196295581571',
    projectId: 'project-wcag',
    storageBucket: 'project-wcag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtySvAqeA7jPX0Obunrb5w8yVlgTC-PlM',
    appId: '1:196295581571:ios:bbafe66064b9c673fd60b6',
    messagingSenderId: '196295581571',
    projectId: 'project-wcag',
    storageBucket: 'project-wcag.firebasestorage.app',
    iosBundleId: 'com.example.znajdzPrzepis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtySvAqeA7jPX0Obunrb5w8yVlgTC-PlM',
    appId: '1:196295581571:ios:bbafe66064b9c673fd60b6',
    messagingSenderId: '196295581571',
    projectId: 'project-wcag',
    storageBucket: 'project-wcag.firebasestorage.app',
    iosBundleId: 'com.example.znajdzPrzepis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPl2cZt27ZqjE3uIj9C-Er6mPLInFkijE',
    appId: '1:196295581571:web:d98c07d6ddfcd92afd60b6',
    messagingSenderId: '196295581571',
    projectId: 'project-wcag',
    authDomain: 'project-wcag.firebaseapp.com',
    storageBucket: 'project-wcag.firebasestorage.app',
    measurementId: 'G-55VD5JL8G7',
  );
}
